version: "3.3"
services:
  slackNotification:
    image: smart-slack-notification-pipe:1.0.0
    build: .
    environment:
      PROJECT_NAME: My Awesome Project
      TEAM_NAME: My Awesome Team
      SLACK_HOOK_URL: ""
      VERSION: 1.0.0
      CHANGELOG: "true"
      BITBUCKET_REPO_SLUG: awesome-service
      BITBUCKET_BUILD_NUMBER: 235