services:
  slackNotification:
    image: raphacps/smart-slack-notification-pipe:1.1.1
    build: .
    environment:
      PROJECT_NAME: My Awesome Project
      TEAM_NAME: My Awesome Team
      SLACK_HOOK_URL: "https://hooks.slack.com/services/AAAAAAAAA/BBBBBBBBBBBBB/XuihifdeHIhifduihIH"
      VERSION: 1.0.0
      CHANGELOG: "true"
      BITBUCKET_EXIT_CODE: 0
      BITBUCKET_REPO_SLUG: awesome-service
      BITBUCKET_BUILD_NUMBER: 235
      BITBUCKET_DEPLOYMENT_ENVIRONMENT: Develop