version: "3.3"
services:
  slackNotification:
    image: raphacps/smart-slack-notification-pipe:1.1.0
    build: .
    environment:
      PROJECT_NAME: My Awesome Project
      TEAM_NAME: My Awesome Team
      SLACK_HOOK_URL: "https://hooks.slack.com/services/999999999/999999999/aaaaaaaaaaaaaaaaaaa"
      VERSION: 1.0.0
      CHANGELOG: "true"
      BITBUCKET_EXIT_CODE: 0
      BITBUCKET_REPO_SLUG: awesome-service
      BITBUCKET_BUILD_NUMBER: 235
      BITBUCKET_DEPLOYMENT_ENVIRONMENT: Develop